### ISSUE TITLE
如何添加Valine评论呢？

### ISSUE THREAD

**Issue by Difers** [Fechin/hexo-theme-diaspora#107]
URL:
Description:我仿照内置的gittalk设置了Valine，但diaspora.js好像并没有调用

**Comment by CCJohny** [comment]
魔改主题中有关gitalk的代码即可
1.diaspora\layout\_partial\post\gitalk.ejs中的代码全部删除，替换为
`<div id="gitalk-container" class="comment link">加载评论</div>`
2.diaspora\layout\_partial\scripts.ejs中的第一行替换为
`<% if (theme.gitalk.enable){ %><%- js(['/Valine.min.js'])%><%}%>`
> （我是将Valine.min.js放置在博客根目录）
3.diaspora\source\js\diaspora.js，找到"case - 1 != tag.indexOf("comment"):"，将下面if与else中的代码全部删除，替换为以下代码：
`				if($('#gitalk-container').data('enable') == true){
					Diaspora.loading(),
					comment = $('#gitalk-container');
					gitalk = new Valine({
						    el: '#gitalk-container' ,
						    appId: '你的Leancloud APPID',
						    appKey: '你的Leancloud APPKEY',
						    notify:false, # 有人回复时的通知
						    verify:true,  # 回复时的验证码
						    avatar:'robohash', 
						    placeholder: '到此一游' 
					})
					$(".comment").removeClass("link")
					gitalk.render('gitalk-container')
					Diaspora.loaded();
				}else{
					Diaspora.loading(),
					comment = $('#gitalk-container');
					gitalk = new Valine({
						    el: '#gitalk-container' ,
						    appId: '你的Leancloud APPID',
						    appKey: '你的Leancloud APPKEY',
						    notify:false, # 有人回复时的通知
						    verify:true,  # 回复时的验证码
						    avatar:'robohash', 
						    placeholder: '到此一游' 
					})
					$(".comment").removeClass("link")
					gitalk.render('gitalk-container')
					Diaspora.loaded();
				}`

**Comment by Difers** [comment]
> 魔改主题中有关gitalk的代码即可
> 1.diaspora\layout_partial\post\gitalk.ejs中的代码全部删除，替换为
> `<div id="gitalk-container" class="comment link">加载评论</div>`
> 2.diaspora\layout_partial\scripts.ejs中的第一行替换为
> `<% if (theme.gitalk.enable){ %><%- js(['/Valine.min.js'])%><%}%>`
> 
> > （我是将Valine.min.js放置在博客根目录）
> 
> 3.diaspora\source\js\diaspora.js，找到`case - 1 != tag.indexOf("comment"):`，将下面if与else中的代码全部删除，替换为以下代码：
> if($('#gitalk-container').data('enable') == true){
> Diaspora.loading(),
> comment = $('#gitalk-container');
> gitalk = new Valine({
> el: '#gitalk-container' ,
> appId: '你的Leancloud APPID',
> appKey: '你的Leancloud APPKEY',
> notify:false, # 有人回复时的通知
> verify:true, # 回复时的验证码
> avatar:'robohash',
> placeholder: '到此一游'
> })
> $(".comment").removeClass("link")
> gitalk.render('gitalk-container')
> Diaspora.loaded();
> }else{
> Diaspora.loading(),
> comment = $('#gitalk-container');
> gitalk = new Valine({
> el: '#gitalk-container' ,
> appId: '你的Leancloud APPID',
> appKey: '你的Leancloud APPKEY',
> notify:false, # 有人回复时的通知
> verify:true, # 回复时的验证码
> avatar:'robohash',
> placeholder: '到此一游'
> })
> $(".comment").removeClass("link")
> gitalk.render('gitalk-container')
> Diaspora.loaded();
> }

谢谢，改好了
