### ISSUE TITLE
您好，希望添加目录和评论功能

### ISSUE THREAD

**Issue by zh-Processor** [Fechin/hexo-theme-diaspora#12]
如题，超喜欢这个主题的，但是自己不会改就很悲伤啦。
所以，麻烦作者大大！

**Comment by Fechin** [comment]
功能已实现，作为可选开关，详见主题配置

**Comment by zh-Processor** [comment]
谢谢作者大大！

Fechin Li <notifications@github.com> 于2018年6月22日周五 下午4:04写道：
