### ISSUE TITLE
提一个小小的功能建议，可以增加音乐随机吗？

### ISSUE THREAD

**Issue by Joyace** [Fechin/hexo-theme-diaspora#13]
配乐是个选择强迫症。
还有可以增加浏览统计吗？
感谢 Fechin .

**Comment by Fechin** [comment]
@Joyace 感谢建议，随机播放音乐的功能已添加，当文章的mp3字段为空时自动随机主题`_config.yml`文件中的mp3列表
主题暂时不添加统计功能，可自行搜索，网上有现成的script脚步，添加很方便

**Comment by Joyace** [comment]
感谢 @Fechin *^_^*
