### ISSUE TITLE
在博客中发现被植入Google广告

### ISSUE THREAD

**Issue by skyone-wzw** [Fechin/hexo-theme-diaspora#133]
![Google广告](https://user-images.githubusercontent.com/73385177/104120599-f95e0e00-5372-11eb-832d-de75e4617cf9.png)
这是我的问题吗？
我从没有想在我的博客里植入广告

**Comment by skyone-wzw** [comment]
`themes\diaspora\layout\_partial\head.ejs` 的38行至47行

**Comment by skyone-wzw** [comment]
![code](https://user-images.githubusercontent.com/73385177/104120819-b43adb80-5374-11eb-8223-2372ec696cae.png)

**Comment by wbs306** [comment]
我这也发现有，干脆移除掉了

**Comment by aecra** [comment]
这个不是广告，这是google_analytics的代码

**Comment by Fechin** [comment]
已移除！
