### ISSUE TITLE
菜单下方的五个按钮图标部分缺失

### ISSUE THREAD

**Issue by WhitemuTeam** [Fechin/hexo-theme-diaspora#142]
菜单中的facebook，twitter图标不能正常加载
这是我的网页https://mu-1303888528.cos-website.ap-guangzhou.myqcloud.com/

**Comment by baiyan0707** [comment]
我的也是，byan.xyz

**Comment by WhitemuTeam** [comment]
现在是八月份了，而在这之前我提交了关于某图标的更新，但是第一个图标仍无法正常加载，所以它移除掉算了
