### ISSUE TITLE
文章添加cover之后主页不能打开

### ISSUE THREAD

**Issue by Neytoph** [Fechin/hexo-theme-diaspora#15]
文章添加cover之后主页不能打开
![image](https://user-images.githubusercontent.com/12654607/44191829-79aac580-a15f-11e8-8096-07c57419aa8b.png)

**Comment by Fechin** [comment]
主题的cover有生效吗

**Comment by Neytoph** [comment]
主题默认的cover是ok的歌曲但是只要我自己制定cover 首页就打不开了 或者打开了是没图的...

**Comment by Fechin** [comment]
请贴一下文章的cover设置
