### ISSUE TITLE
Banner will appear in post page as well when visiting site on mobile phone

### ISSUE THREAD

**Issue by alex123bob** [Fechin/hexo-theme-diaspora#17]
When I visit my blog based on your theme in mobile browser, everything goes well in home page. However, banner picture will display in post page if I click post from home page.

Not sure if this is resulted from your theme, would you mind taking a look at it?

Thanks.

**Comment by alex123bob** [comment]
@Fechin I have solved this issue in my local. You can simply remove `return false;` in switch loop at file `diaspora.js`, line 388. I haven't tested on other `return false` yet, but from my perspective, most of them could be removed. Thanks.

**Comment by alex123bob** [comment]
![image](https://user-images.githubusercontent.com/5180511/44439759-9af43180-a5f7-11e8-875a-c789545806bd.png)
Something added up for this issue. I was wrong in the first time, the root cause of this defect is from the place shown in picture above. To check if `#preview` container is existed or not, we'd better not use `left` to check. Coz in mobile browser, `left` will be set as `auto` in the second time that event triggered in `preview` functionality. Hence, we use class `show`'s existence to judge if preview is visible or not.

@Fechin

**Comment by Fechin** [comment]
Congratulations! 
What browser do you use, this problem does not appear on my mobile browser.

**Comment by alex123bob** [comment]
@Fechin mobile safari, mobile chrome. It's shown in any mobile browser as I can see. And easy to reproduce, simply go into home page, and click menu button at the top right corner, choose `whoami`, then you will be directed into corresponding page. In mobile browser, you'll find that `#container` pops up after several milliseconds. The root cause is just as my aforementioned comment. You can check it for reference.

**Comment by Fechin** [comment]
The problem has been resolved, close the issue
