### ISSUE TITLE
直接引用控制台报错---求助！！

### ISSUE THREAD

**Issue by web-songsong** [Fechin/hexo-theme-diaspora#19]
网址：websong.xin
**问题：**
* 随意点入blog后控制台报错。那个`undefined`是哪个参数，我没有找到，怎么关闭解决报错问题？
* 打包文件后放在服务器上。点击进入blog，路由切换，没有刷新网页，为什么会请求这个接口？
> 麻烦了，如果有时间麻烦看一下这个问题。谢谢

**Comment by Fechin** [comment]
undefined链接是audio标签生成的，文章没设置音乐，所以src地址是undefined

**Comment by web-songsong** [comment]
非常感谢，问题已解决，没有注意这个问题。
