### ISSUE TITLE
TOC问题

### ISSUE THREAD

**Issue by KeiferJu** [Fechin/hexo-theme-diaspora#24]
您好,如果多级,感觉渲染时第二级之下的目录的会放到标签外,这个我试着改,没成功.

**Comment by KeiferJu** [comment]
![tim 20180921103217](https://user-images.githubusercontent.com/20491834/45857325-c0a55f80-bd8a-11e8-9c07-9a27633ff23d.png)

**Comment by KeiferJu** [comment]
![tim 20180921103125](https://user-images.githubusercontent.com/20491834/45857337-c8fd9a80-bd8a-11e8-85a3-44f9f7ab6591.png)

**Comment by Fechin** [comment]
是不是内容太多了，如果ToC支持滚动是否还有这个问题

**Comment by liHeart** [comment]
遇到同样问题，目录层级最大3层，内容也不算多，但出现跟@KeiferJu一样的前端样式。同一h级别的标题应该是同一个<ol></ol>的子元素，但却有一部分成了兄弟<li>元素，但是看了下ejs里面只是调用了一下toc()函数，不明白为什么会出现这个问题

**Comment by liHeart** [comment]
找到原因了，出现这个问题是因为在markdown里面设置标题级别时出现了隔级设置，比如一个二级标题底下的子标题设置成了四级标题，然后hexo渲染成html时使用了toc函数（位于博客根路径/node_modules/hexo/lib/plugins/helper/toc.js），toc函数里面使用了[cheerio](https://github.com/cheeriojs/cheerio)插件，而这个插件是不支持这种隔级标题的，所以会出现问题。我修改了自己文章的标题层级之后页面展示效果正常了
