### ISSUE TITLE
右侧菜单问题,音乐播放器问题

### ISSUE THREAD

**Issue by ferried** [Fechin/hexo-theme-diaspora#27]
具体见：https://ferried.github.io/2018/10/14/pysupport/
太长了
音乐播放器从主页点进去可以自动播放，刷新后无法自动播放js报错

**Comment by Fechin** [comment]
ToC支持滚动，已修改；
无法自动播放的问题没能复现，贴个截图看看。

**Comment by ferried** [comment]
<img width="1367" alt="qq20181014-121247 2x" src="https://user-images.githubusercontent.com/26159886/46938043-520ba700-d095-11e8-96bf-622027914229.png">

如图，在开启自动播放情况下直接输入网址:https://ferried.github.io/2018/10/14/pysupport/
play错误，可能是不是从主页跳转过来，少加载了js?

**Comment by ferried** [comment]
问题找到了,google的问题

**Comment by Fechin** [comment]
Google对自动播放制定了新的政策，要么静音自动播放，要么用户跟页面已经有过交互。所以这个功能鸡肋了「：摊手」

https://developers.google.com/web/updates/2017/09/autoplay-policy-changes
