### ISSUE TITLE
希望作者开发文章大纲的模块

### ISSUE THREAD

**Issue by TyCoding** [Fechin/hexo-theme-diaspora#29]
作者开发的主题非常漂亮了，非常感谢作者，不过希望作者有时间开发一下文章大纲的列表模块，在文章右侧一个滑动的Markdown标题视图大纲这样的效果。

**Comment by Fechin** [comment]
TOC模块可以解决你的问题吗

**Comment by TyCoding** [comment]
> TOC模块可以解决你的问题吗

请问这个TOC模块怎么启用呢？我在文档中没有看到介绍呀，部署的项目文章页中也没有显示

**Comment by Fechin** [comment]
修改主题下的`_config.yml`
```
# 是否显示目录
TOC: true
```

https://github.com/Fechin/hexo-theme-diaspora#%E4%B8%BB%E9%A2%98%E9%85%8D%E7%BD%AE

**Comment by TyCoding** [comment]
抱歉抱歉，非常非常感谢，这个TOC目录很好看
