### ISSUE TITLE
用作者的模板写，页面会出现title,date,tags?求解

### ISSUE THREAD

**Issue by kevinfu2048** [Fechin/hexo-theme-diaspora#30]
<img width="960" alt="2" src="https://user-images.githubusercontent.com/38284579/47917875-d52a5b00-dee5-11e8-9ce0-89be86b4cb56.PNG">
<img width="921" alt="3" src="https://user-images.githubusercontent.com/38284579/47917878-d6f41e80-dee5-11e8-9eee-7713862b002b.PNG">

**Comment by kevinfu2048** [comment]
<img width="709" alt="default" src="https://user-images.githubusercontent.com/38284579/47953671-beeece80-dfbb-11e8-8dc7-927455940dc1.PNG">

**Comment by kevinfu2048** [comment]
是这样用模板的吗

**Comment by Fechin** [comment]
你好，这种情况是md文件没有被hexo正常编译，跟主题无关，建议你换个编辑器，确认md文件编码是否正确，再试试。
