### ISSUE TITLE
你好, 请问主题能否像next主题那样添加功能

### ISSUE THREAD

**Issue by mirrormingzZ** [Fechin/hexo-theme-diaspora#34]
比如这些...
在右上角或者左上角实现fork me on github
添加RSS
添加动态背景
实现点击出现桃心效果
修改文章内链接文本样式
修改文章底部的那个带#号的标签
在每篇文章末尾统一添加“本文结束”标记
修改作者头像并旋转
博文压缩
修改“代码块自定义样式
侧边栏社交小图标设置
主页文章添加阴影效果
在网站底部加上访问量
添加热度
网站底部字数统计
添加 README.md 文件
设置网站的图标Favicon
实现统计功能
添加顶部加载条
在文章底部增加版权信息
添加网易云跟帖(跟帖关闭，已失效，改为来必力)
隐藏网页底部powered By Hexo / 强力驱动
修改网页底部的桃心
文章加密访问
添加jiathis分享
博文置顶
修改字体大小
修改打赏字体不闪动
自定义鼠标样式
为博客加上萌萌的宠物
DaoVoice 在线联系
点击爆炸效果

**Comment by Fechin** [comment]
本主题主打简洁，干净，风格跟next完全不一样，并不希望打造成全能的博客主题，小而美最好！
如果功能型主题更适合你的内容，移步next是你最好的选择。

**Comment by mirrormingzZ** [comment]
这个主题很漂亮 , 如果能添加点功能就更好了鸭

**Comment by Fechin** [comment]
了解你的想法，在不破坏主题风格的情况下，我会酌情添加

**Comment by mirrormingzZ** [comment]
希望能添加上DaoVoice 在线联系和动态背景 , 谢谢大佬

**Comment by stevenjoezhang** [comment]
Hexo 已实现文章置顶参数： https://github.com/hexojs/hexo-generator-index/pull/51
