### ISSUE TITLE
文章和封面始终保持全局的封面

### ISSUE THREAD

**Issue by SukiYume** [Fechin/hexo-theme-diaspora#38]
新建文章添加cover，不管是使用'/img/xxx.jpg'还是'https://xxxx.xxx.xxx/xxx.jpg'，首页封面以及其他文章始终是默认的全局封面，请问一下这个问题该怎么处理？

**Comment by SukiYume** [comment]
突然变成x网链接？

**Comment by Fechin** [comment]
贴一下网址和文章的frontMatter

**Comment by Cirzear** [comment]
+1

**Comment by Cirzear** [comment]
重新发布了几次之后就好了

**Comment by Fechin** [comment]
@SukiYume 问题解决了吗

**Comment by SukiYume** [comment]
不好意思，好久没用hexo，现在用这个主题的时候没办法generate了…我在排查原因

**Comment by SukiYume** [comment]
嗯，我又重新建了个站，试了一下，再没出现这个问题。万分感谢。
另外，关于这个主题，有没有相册页面呀……

**Comment by Fechin** [comment]
没有相册页面
