### ISSUE TITLE
Font type change in Mobile Ends

### ISSUE THREAD

**Issue by Moo-YewTsing** [Fechin/hexo-theme-diaspora#41]
Hello, I have changed the setting related to font family in the "**Diaspora.css**" file. Also, to make sure those fonts are independent of machines.  I added the correspondent link from Google Fonts to the "**head.ejs**" in "./layout/_partial/".

Using my desktop browser to check my website. All looks good and fit my expectation. However, in a mobile end, that is my iPhone, the font type seems not to change at all.

Could you give me some advise about how to solve the problem. Appreciate!

BTW, your theme is really amazing. If consider more about the Anglophone users, I believe it would be better.

Thanks! Have a nice day!
Regard,

**Comment by Fechin** [comment]
Maybe the font file is not completely downloaded to success, or try another browser.
