### ISSUE TITLE
左上角logo不见

### ISSUE THREAD

**Issue by xuyichenmo** [Fechin/hexo-theme-diaspora#43]
如题，左上角logo不见。
网站：https://xumo.gitee.io/abcd/
已经尝试重新克隆文件，仍然存在问题
![1.png](https://i.loli.net/2019/02/05/5c59764307bc2.png)
![2.png](https://i.loli.net/2019/02/05/5c5976d55387f.png)

**Comment by Fechin** [comment]
我在你网站的diaspora.css文件中没看到.image-logo的样式代码，请确认diaspora.css是否是最新的

**Comment by hongjun500** [comment]
> 我在你网站的diaspora.css文件中没看到图像配-标志的样式代码，请确认diaspora.css是否是最新的

大佬你好，我clone你的最新版，然后把你的原先logo.png重新命名为别的，然后自己弄了一张logo.png,按常理来说应该可以，结果哪里显示一片空白，在开发人员工具里手动改成你的却又能显示。。。重新启动也没用

**Comment by Fechin** [comment]
> > 我在你网站的diaspora.css文件中没看到图像配-标志的样式代码，请确认diaspora.css是否是最新的
> 
> 大佬你好，我clone你的最新版，然后把你的原先logo.png重新命名为别的，然后自己弄了一张logo.png,按常理来说应该可以，结果哪里显示一片空白，在开发人员工具里手动改成你的却又能显示。。。重新启动也没用

是不是缓存的问题，检查一下你的那张图片正常吗，什么颜色？

**Comment by ChinLong** [comment]
兄弟，这个问题我也遇到了。
原因是你设置了 config.root 。

**Comment by hongjun500** [comment]
> > > 我在你网站的diaspora.css文件中没看到图像配 - 标志的样式代码，请确认diaspora.css是否是最新的
> > 
> > 
> > 大佬你好，我克隆你的最新版，然后把你的原先logo.png重新命名为别的，然后自己弄了一张logo.png，按常理来说应该可以，结果哪里显示一片空白，在开发人员工具里手动改成你的却又能显示...重新启动也没用
> 
> 是不是缓存的问题，检查一下你的那张图片正常吗，什么颜色？

好了，搞定了！这个细节比较刁钻，就是图片的透明度！！！在文件夹里看到的原先你那个“常也”是白底黑字，其实不然，当用sublime里看到却是有着灰白相间的底纹(透明度)
