### ISSUE TITLE
通过链接打开文章后点击左上角小房子没法直接进入主页

### ISSUE THREAD

**Issue by ovaso** [Fechin/hexo-theme-diaspora#45]
> 主页地址：http://hiems.coding.me/nuts/ 
## case1 不正常情况
如果需要分享页面给朋友的话直接将链接复制粘贴给朋友，朋友看完了文章想去主页看看，这时候点击左上角的小房子图标不会指向主页，而是简单的指向了http://hiems.coding.me。
## case2 正常情况
如果通过主页进入文章界面，此时点击左上角图标则可以正常返回主页。
## case3 
查看了您的博客，不会出现此状况。而且发现您的博客从文章页跳转到主页时没有过渡动画，不会出现横向移动的效果。

**Comment by Fechin** [comment]
已修复，请修改hexo的`_config.yml`文件（注意：不是主题的配置文件）的`url`字段。

如：
```
url: http://hiems.coding.me/nuts/
```
