### ISSUE TITLE
文章封面只显示部分内容

### ISSUE THREAD

**Issue by hongjun500** [Fechin/hexo-theme-diaspora#56]
大佬你好，如何设置文章封面只显示部分的内容啊，我在网上查阅用哪个“”在md文件中进行设置，发现还是没有效果啊

**Comment by Fechin** [comment]
是指标题下的文章摘要吗，默认截取80个字符

**Comment by hongjun500** [comment]
> 是指标题下的文章摘要吗，默认截取80个字符
是的是的，就是这个意思。但我还是想人为控制下这个内容的长度，请问这样能行吗

**Comment by Fechin** [comment]
修改这个文件的第8行：`themes/diaspora/layout/_partial/post/item.ejs`

**Comment by hongjun500** [comment]
> 修改这个文件的第8行：`themes/diaspora/layout/_partial/post/item.ejs`

ok,感谢大佬
