### ISSUE TITLE
adsbygoogle.js和amp-auto-ads-0.1.js

### ISSUE THREAD

**Issue by imleft** [Fechin/hexo-theme-diaspora#57]
GET https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js net::ERR_BLOCKED_BY_CLIENT
www.lohmo.com/:26 GET https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js net::ERR_BLOCKED_BY_CLIENT

**Comment by Fechin** [comment]
可忽略
