### ISSUE TITLE
添加新文章之后，设置了cover，但是不显示图片

### ISSUE THREAD

**Issue by chuzhaozhi** [Fechin/hexo-theme-diaspora#59]
新增文章之后，会显示在最上面，只有黑色遮罩和文章标题显示，设置的cover图片没有加载出来
<img width="1392" alt="1" src="https://user-images.githubusercontent.com/18342190/55389304-8dc4fb00-5567-11e9-992e-5dd80798f10b.png">
求指教

**Comment by Fechin** [comment]
检查一下cover地址

**Comment by Fechin** [comment]
控制台是否保存，是不是跨域了

**Comment by ZkhEight** [comment]
同样的问题，cover地址没错。。

**Comment by chuzhaozhi** [comment]
![image](https://user-images.githubusercontent.com/18342190/55445572-96acdf80-55ee-11e9-843a-4c84fcfdc01b.png)
报错了

**Comment by Fechin** [comment]
跨域了，大哥

**Comment by Suny95** [comment]
我现在也有这个问题, 只要新文章设置cover就会出现跟你这一样的错误

**Comment by yun0628** [comment]
大哥 跨域了 怎么处理啊  难道要自己弄个服务器嘛 还是在域名配置中 解析 ？ @Fechin
