### ISSUE TITLE
建议将文章的markdown样式修改一下

### ISSUE THREAD

**Issue by lorki** [Fechin/hexo-theme-diaspora#6]
关于样式可以参考一下 http://anatole.munen.cc/2013/12/25/tag-plugins/ 看上去还是比较舒服的,至少相比现在代码片段黑框无高亮来说是好多了。
它的github地址：https://github.com/Ben02/hexo-theme-Anatole

**Comment by Fechin** [comment]
感谢建议，提供的参考样式跟本主题样式相差太大，为了保证本主题的特性，没什么参考价值
另外，我已经在表格响应式，标题大小，引用块等样式做了微调，麻烦更新后再看下，有细节上的建议欢迎列出来。

**Comment by lorki** [comment]
主要是看功能细节。。主要是代码高亮和自动换行这些啊。不是说要做成一模一样的。。

**Comment by Fechin** [comment]
萝卜白菜，各有所爱，觉得不爽fork一份自己改，打造你最中意的样式。
