### ISSUE TITLE
希望能够添加站内搜索功能

### ISSUE THREAD

**Issue by lichen0501** [Fechin/hexo-theme-diaspora#62]
有时候文章多了，分类标签多了不好搜索
https://blog.csdn.net/qq_40265501/article/details/80030627
能不能加一个开关之类的，就像文章里面那样，用本地搜索

**Comment by zzReno** [comment]
对，感觉站内搜索是个非常重要的功能

**Comment by youngjuning** [comment]
希望加上，这个功能太重要了

**Comment by Fechin** [comment]
已添加搜索功能，配置时注意查看README
