### ISSUE TITLE
关于mp3播放的问题

### ISSUE THREAD

**Issue by HNightMan** [Fechin/hexo-theme-diaspora#65]
请问我设置的音乐播放的时候开头的地方声音很奇怪是怎么回事，刚开始一瞬间声音是正常的，突然变小然后慢慢增大，所以开头那一瞬间的大声听起来就很奇怪

**Comment by HNightMan** [comment]
还有请问可以添加友链吗

**Comment by Fechin** [comment]
声音从小变大才对呀，防止声音太大被吓着

**Comment by Fechin** [comment]
主题不支持配置友链，你可以新建个页面，在页面里写链接
