### ISSUE TITLE
归档页面时间轴上只能显示最近的10条记录，怎么让它显示全部的发布记录呢？

### ISSUE THREAD

**Issue by Tonynovtop** [Fechin/hexo-theme-diaspora#68]
URL:https://fech.in/
Description:您好，归档页面时间轴上只能显示最近发布的10条文章记录，如何让它显示全部的发布记录呢？
![图片](https://user-images.githubusercontent.com/46803855/57511619-438c2200-733c-11e9-9532-455516b4cffc.png)

**Comment by Fechin** [comment]
问题已修复，请更新主题
