### ISSUE TITLE
希望增加mathjax支持

### ISSUE THREAD

**Issue by KosumosuL** [Fechin/hexo-theme-diaspora#72]
URL:
Description: 希望增加mathjax支持

**Comment by Fechin** [comment]
库文件大，需求不够大众，所以暂时不打算支持，你可以fork一份自己定制主题哈

**Comment by MakerGYT** [comment]
@KosumosuL  试试[markdown-it-latex2img](https://github.com/MakerGYT/markdown-it-latex2img#Hexo)
