### ISSUE TITLE
hexo g ERROR: path.startsWith is not a function

### ISSUE THREAD

**Issue by februarysea** [Fechin/hexo-theme-diaspora#74]
之前一切正常，想给文章换一张封面图渲染的时候出现了这样的问题，请问应该如何解决？

```
ERROR /Users/februarysea/blog/themes/diaspora/layout/index.ejs:5
    3|     <%- partial("_partial/screen", null, {cache: false}) %>
    4|     <div id="primary">
 >> 5|         <%- partial('_partial/list', {start: 1}) %>
    6|     </div>
    7|     <% if (page.total > 1 && page.next_link){ %>
    8|     <div id="pager"><a href="<%- url_for(page.next_link) %>" class="more">加载更多</a></div>

/Users/februarysea/blog/themes/diaspora/layout/_partial/list.ejs:7
    5|     }
    6| %>
 >> 7| <%- partial('post/item', {post: post}) %>
    8| <% }) %>

/Users/februarysea/blog/themes/diaspora/layout/_partial/post/item.ejs:3
    1| <div class="post">
    2|     <a href="<%- url_for(post.path) %>" title="<%- post.title || "Untitled" %>">
 >> 3|         <%- image_tag(post.cover || theme.cover, {class: "cover", width: 680, height: 440}) %>
    4|     </a>
    5|     <div class="else">
    6|         <p><%- post.date.locale("zh-cn").format("MMMM DD, YYYY") %></p>

path.startsWith is not a function
TypeError: /Users/februarysea/blog/themes/diaspora/layout/index.ejs:5
    3|     <%- partial("_partial/screen", null, {cache: false}) %>
    4|     <div id="primary">
 >> 5|         <%- partial('_partial/list', {start: 1}) %>
    6|     </div>
    7|     <% if (page.total > 1 && page.next_link){ %>
    8|     <div id="pager"><a href="<%- url_for(page.next_link) %>" class="more">加载更多</a></div>

/Users/februarysea/blog/themes/diaspora/layout/_partial/list.ejs:7
    5|     }
    6| %>
 >> 7| <%- partial('post/item', {post: post}) %>
    8| <% }) %>

/Users/februarysea/blog/themes/diaspora/layout/_partial/post/item.ejs:3
    1| <div class="post">
    2|     <a href="<%- url_for(post.path) %>" title="<%- post.title || "Untitled" %>">
 >> 3|         <%- image_tag(post.cover || theme.cover, {class: "cover", width: 680, height: 440}) %>
    4|     </a>
    5|     <div class="else">
    6|         <p><%- post.date.locale("zh-cn").format("MMMM DD, YYYY") %></p>

path.startsWith is not a function
    at Object.urlForHelper (/Users/februarysea/blog/node_modules/hexo/lib/plugins/helper/url_for.js:6:31)
    at Object.imageTagHelper (/Users/februarysea/blog/node_modules/hexo/lib/plugins/helper/image_tag.js:7:15)
    at eval (eval at compile (/Users/februarysea/blog/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:16:17)
    at returnedFn (/Users/februarysea/blog/node_modules/ejs/lib/ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (/Users/februarysea/blog/node_modules/hexo/lib/theme/view.js:121:22)
    at Theme._View.View.View.renderSync (/Users/februarysea/blog/node_modules/hexo/lib/theme/view.js:49:23)
    at Object.partial (/Users/februarysea/blog/node_modules/hexo/lib/plugins/helper/partial.js:38:15)
    at eval (eval at compile (/Users/februarysea/blog/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:18:17)
    at Model._Query.Query.Query.forEach (/Users/februarysea/blog/node_modules/warehouse/lib/query.js:42:5)
    at eval (eval at compile (/Users/februarysea/blog/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:10:37)
    at returnedFn (/Users/februarysea/blog/node_modules/ejs/lib/ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (/Users/februarysea/blog/node_modules/hexo/lib/theme/view.js:121:22)
    at Theme._View.View.View.renderSync (/Users/februarysea/blog/node_modules/hexo/lib/theme/view.js:49:23)
    at Object.partial (/Users/februarysea/blog/node_modules/hexo/lib/plugins/helper/partial.js:38:15)
    at eval (eval at compile (/Users/februarysea/blog/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:15:17)
    at returnedFn (/Users/februarysea/blog/node_modules/ejs/lib/ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (/Users/februarysea/blog/node_modules/hexo/lib/theme/view.js:125:48)
    at Theme._View.View.View.render (/Users/februarysea/blog/node_modules/hexo/lib/theme/view.js:30:15)
    at route.set (/Users/februarysea/blog/node_modules/hexo/lib/hexo/index.js:394:29)
    at tryCatcher (/Users/februarysea/blog/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/februarysea/blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/februarysea/blog/node_modules/hexo/lib/hexo/router.js:134:3)
 
```

**Comment by hongjun500** [comment]
> 之前一切正常，想给文章换一张封面图渲染的时候出现了这样的问题，请问应该如何解决？
> 
> ```
> ERROR /Users/februarysea/blog/themes/diaspora/layout/index.ejs:5
>     3|     <%- partial("_partial/screen", null, {cache: false}) %>
>     4|     <div id="primary">
>  >> 5|         <%- partial('_partial/list', {start: 1}) %>
>     6|     </div>
>     7|     <% if (page.total > 1 && page.next_link){ %>
>     8|     <div id="pager"><a href="<%- url_for(page.next_link) %>" class="more">加载更多</a></div>
> 
> /Users/februarysea/blog/themes/diaspora/layout/_partial/list.ejs:7
>     5|     }
>     6| %>
>  >> 7| <%- partial('post/item', {post: post}) %>
>     8| <% }) %>
> 
> /Users/februarysea/blog/themes/diaspora/layout/_partial/post/item.ejs:3
>     1| <div class="post">
>     2|     <a href="<%- url_for(post.path) %>" title="<%- post.title || "Untitled" %>">
>  >> 3|         <%- image_tag(post.cover || theme.cover, {class: "cover", width: 680, height: 440}) %>
>     4|     </a>
>     5|     <div class="else">
>     6|         <p><%- post.date.locale("zh-cn").format("MMMM DD, YYYY") %></p>
> 
> path.startsWith is not a function
> TypeError: /Users/februarysea/blog/themes/diaspora/layout/index.ejs:5
>     3|     <%- partial("_partial/screen", null, {cache: false}) %>
>     4|     <div id="primary">
>  >> 5|         <%- partial('_partial/list', {start: 1}) %>
>     6|     </div>
>     7|     <% if (page.total > 1 && page.next_link){ %>
>     8|     <div id="pager"><a href="<%- url_for(page.next_link) %>" class="more">加载更多</a></div>
> 
> /Users/februarysea/blog/themes/diaspora/layout/_partial/list.ejs:7
>     5|     }
>     6| %>
>  >> 7| <%- partial('post/item', {post: post}) %>
>     8| <% }) %>
> 
> /Users/februarysea/blog/themes/diaspora/layout/_partial/post/item.ejs:3
>     1| <div class="post">
>     2|     <a href="<%- url_for(post.path) %>" title="<%- post.title || "Untitled" %>">
>  >> 3|         <%- image_tag(post.cover || theme.cover, {class: "cover", width: 680, height: 440}) %>
>     4|     </a>
>     5|     <div class="else">
>     6|         <p><%- post.date.locale("zh-cn").format("MMMM DD, YYYY") %></p>
> 
> path.startsWith is not a function
>     at Object.urlForHelper (/Users/februarysea/blog/node_modules/hexo/lib/plugins/helper/url_for.js:6:31)
>     at Object.imageTagHelper (/Users/februarysea/blog/node_modules/hexo/lib/plugins/helper/image_tag.js:7:15)
>     at eval (eval at compile (/Users/februarysea/blog/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:16:17)
>     at returnedFn (/Users/februarysea/blog/node_modules/ejs/lib/ejs.js:653:17)
>     at Theme._View.View._compiledSync.locals [as _compiledSync] (/Users/februarysea/blog/node_modules/hexo/lib/theme/view.js:121:22)
>     at Theme._View.View.View.renderSync (/Users/februarysea/blog/node_modules/hexo/lib/theme/view.js:49:23)
>     at Object.partial (/Users/februarysea/blog/node_modules/hexo/lib/plugins/helper/partial.js:38:15)
>     at eval (eval at compile (/Users/februarysea/blog/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:18:17)
>     at Model._Query.Query.Query.forEach (/Users/februarysea/blog/node_modules/warehouse/lib/query.js:42:5)
>     at eval (eval at compile (/Users/februarysea/blog/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:10:37)
>     at returnedFn (/Users/februarysea/blog/node_modules/ejs/lib/ejs.js:653:17)
>     at Theme._View.View._compiledSync.locals [as _compiledSync] (/Users/februarysea/blog/node_modules/hexo/lib/theme/view.js:121:22)
>     at Theme._View.View.View.renderSync (/Users/februarysea/blog/node_modules/hexo/lib/theme/view.js:49:23)
>     at Object.partial (/Users/februarysea/blog/node_modules/hexo/lib/plugins/helper/partial.js:38:15)
>     at eval (eval at compile (/Users/februarysea/blog/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:15:17)
>     at returnedFn (/Users/februarysea/blog/node_modules/ejs/lib/ejs.js:653:17)
>     at Theme._View.View._compiled.locals [as _compiled] (/Users/februarysea/blog/node_modules/hexo/lib/theme/view.js:125:48)
>     at Theme._View.View.View.render (/Users/februarysea/blog/node_modules/hexo/lib/theme/view.js:30:15)
>     at route.set (/Users/februarysea/blog/node_modules/hexo/lib/hexo/index.js:394:29)
>     at tryCatcher (/Users/februarysea/blog/node_modules/bluebird/js/release/util.js:16:23)
>     at /Users/februarysea/blog/node_modules/bluebird/js/release/method.js:15:34
>     at RouteStream._read (/Users/februarysea/blog/node_modules/hexo/lib/hexo/router.js:134:3)
>  
> ```

这个其实答案你已经给出了：之前一切正常，后面加封面图时出了问题.......那么应该就是加封面图时md语法错误，我之前添加音乐外链的时候为了给那首歌记录一下歌名，在外链后面注释了歌名保存一下结果就出错了，你检查一下对应地方的语法有没有错，图片和音乐前后都不能添加别的其它(注释了也不行)

**Comment by Fechin** [comment]
是的，检查一下封面的配置
