### ISSUE TITLE
怎么为每一篇文章单独配置图片???

### ISSUE THREAD

**Issue by CainLuo** [Fechin/hexo-theme-diaspora#75]
URL: https://cainluo.github.io/iOSDevelopment/
Description: 看了一下说明, 也没有告诉说怎么单独为每一篇文章精确的配置预览图, 请问如何操作?

**Comment by Antrovirens** [comment]
在issue#25里面有说的，把图片放source里面，然后在新建的页面头部可以设置图片路径的，下面有两个例子
---
title: My awesome title
date: 2016-10-12 18:38:45
cover: http://domain.com/awesome.jpg
---
---
title: a title
date: 2019-07-14 13:10:29
cover: img/cover20190714.jpg
---

**Comment by CainLuo** [comment]
@Antrovirens 哦哦哦，好的，谢谢啦
