### ISSUE TITLE
gitalk的配置问题

### ISSUE THREAD

**Issue by CainLuo** [Fechin/hexo-theme-diaspora#76]
URL: https://cainluo.github.io
Description: gitalk的配置问题

 我看了一下其他人的配置, 感觉也是这样子配置的, 但是发现还是不行
<img width="627" alt="image" src="https://user-images.githubusercontent.com/8857291/61527885-6b90b380-aa58-11e9-8f1c-a12f46c2a063.png">

![image](https://user-images.githubusercontent.com/8857291/61527914-8400ce00-aa58-11e9-99ed-e78be7926a95.png)

还会提示我未初始化.....这个怎么解决???

![image](https://user-images.githubusercontent.com/8857291/61527936-911dbd00-aa58-11e9-9609-245136931cf1.png)

**Comment by Fechin** [comment]
URL不带中文试试？

**Comment by CainLuo** [comment]
> URL不带中文试试？

哪个URL不带中文?

**Comment by CainLuo** [comment]
我尝试把js文件里的locationname添加了decodeURI或者是md5一下, 发现并没有什么用

**Comment by CainLuo** [comment]
现在我改成了https://cainluo.github.io/2019/07/15/RxSwift_hello_RxSwift/还是不能显示~~

**Comment by hongjun500** [comment]
> 网址：[https](https://cainluo.github.io)
> ：//cainluo.github.io说明：gitalk的配置问题
> 
> 我看了一下其他人的配置，感觉也是这样子配置的，但是发现还是不行
> <img alt="图片" width="627" src="https://user-images.githubusercontent.com/8857291/61527885-6b90b380-aa58-11e9-8f1c-a12f46c2a063.png">
> 
> ![图片](https://user-images.githubusercontent.com/8857291/61527914-8400ce00-aa58-11e9-99ed-e78be7926a95.png)
> 
> 还会提示我未初始化.....这个怎么解决???
> 
> ![图片](https://user-images.githubusercontent.com/8857291/61527936-911dbd00-aa58-11e9-9609-245136931cf1.png)

![image](https://user-images.githubusercontent.com/44798877/62469174-504cd480-b7ca-11e9-940c-b8242260104b.png)
你这三个地方，前面两个有单引号，[]（但是你删了），然后还有个id的值你就遵循博主原来默认的不要动，修改一下；最后自己访问时用自己!!!的这个github号登录一下(切记,已踩了坑)

**Comment by CainLuo** [comment]
> > 网址：[https](https://cainluo.github.io)
> > ：//cainluo.github.io说明：gitalk的配置问题
> > 我看了一下其他人的配置，感觉也是这样子配置的，但是发现还是不行
> > <img alt="图片" width="627" src="https://user-images.githubusercontent.com/8857291/61527885-6b90b380-aa58-11e9-8f1c-a12f46c2a063.png">
> > ![图片](https://user-images.githubusercontent.com/8857291/61527914-8400ce00-aa58-11e9-99ed-e78be7926a95.png)
> > 还会提示我未初始化.....这个怎么解决???
> > ![图片](https://user-images.githubusercontent.com/8857291/61527936-911dbd00-aa58-11e9-9609-245136931cf1.png)
> 
> ![image](https://user-images.githubusercontent.com/44798877/62469174-504cd480-b7ca-11e9-940c-b8242260104b.png)
> 你这三个地方，前面两个有单引号，[]（但是你删了），然后还有个id的值你就遵循博主原来默认的不要动，修改一下；最后自己访问时用自己!!!的这个github号登录一下(切记,已踩了坑)

可以了, 谢谢大佬~~~

**Comment by acdiost** [comment]
我有引号也提示。自己评论一个就出来了。

https://fech.in/2017/5-linux-command-surprised/
这篇文章也是这样。
Related Issues not found
Please contact @Fechin to initialize the comment

**Comment by acdiost** [comment]
需要自己登录点一下，进行初始化。
