### ISSUE TITLE
域名备案号

### ISSUE THREAD

**Issue by hongjun500** [Fechin/hexo-theme-diaspora#78]
URL:
Description:
请问在哪里添加域名备案号呢

**Comment by Fechin** [comment]
没有配置项，需要修改这个文件：/layout/_partial/menu.ejs

**Comment by hongjun500** [comment]
加一个footer的模块对吧

**Comment by Fechin** [comment]
可以，也可以直接修改copyright这块内容

**Comment by hongjun500** [comment]
妥

**Comment by hongjun500** [comment]
> 没有配置项，需要修改这个文件：/layout/_partial/menu.ejs

我突然想到了素锦的方式，直接在/layout/index.ejs --最后一行添加了一段文本保证了主页和每个页面都有显示，感谢大佬！
