### ISSUE TITLE
你好，能否帮助我添加一个搜索功能和换页

### ISSUE THREAD

**Issue by 775854115** [Fechin/hexo-theme-diaspora#8]
当我第一次看到你的主题的时候我，我感到很惊艳，放弃了原来的主题，更换到你的主题。但是我发现有个问题，就是当我日记变多的时候，无法快速搜索到以前的日志。另外，你这一页会显示多少个日志，会自动排序到下一页吗？还有个问题，就是二维码的问题。它是如何做到的。因为我不知道在哪里能联系到你，所以就在这留言了。我希望能得到你的帮助

**Comment by Fechin** [comment]
喜欢记得点小星星哦，搜索功能目前有个项目，考虑加上来。分页功能当文章超过10篇会出现“加载更多”的按钮。

**Comment by Fechin** [comment]
你的博客内容是认真的吗，图片和关于跟我的这么像😂

**Comment by 775854115** [comment]
我这个博客是用来做备份的，好的文章啥的留着，方便自己再次阅读😝。图片啥的别在意
