### ISSUE TITLE
关于主题内article.ejs的问题

### ISSUE THREAD

**Issue by STASWIT** [Fechin/hexo-theme-diaspora#90]
我想对我的博客添加一些有助于保护文章内容的插件，但是这些插件需要修改article.ejs文件，我打开这个文件后，发现里面的内容和正常的hexo主题不同，修改后会报错，我不知道这个问题如何解决。难道我只能用主题内已有设置？

**Comment by Fechin** [comment]
文章的源码对应文件：layout/_partial/post/article.ejs
