### ISSUE TITLE
本地目录怎么配置？

### ISSUE THREAD

**Issue by Mr-XiaoLiang** [Fechin/hexo-theme-diaspora#92]
在主页右上角是菜单按钮，点击后可以打开一个目录。
我有看到配置文件的“menu”可以配置，但是我只有网址能够成功配置。一旦设置为博客内部的地址就不成功了。
请问这个相对地址的起点目录是哪里？
是项目的source吗？
比如说，我配置是：
```
menu:
  about: /about
```
我在source/about.md的文件，点击访问不成功
在themes/diaspora/source/about.md的文件，点击也是访问不成功

**Comment by hopehero** [comment]
直接用项目的就可以了 我就是直接用的项目的

**Comment by Fechin** [comment]
这里对应about目录：themes/diaspora/source/about/index.md
```
hexo new page about
```
