### ISSUE TITLE
如何在主页添加页脚内容

### ISSUE THREAD

**Issue by noseparte** [Fechin/hexo-theme-diaspora#93]
URL:  http://www.almost-famous.cn/
Description: 域名备案后管局要求添加备案号在页脚。有没有对应的插件或者组件

**Comment by noseparte** [comment]
![image](https://user-images.githubusercontent.com/30165939/71428302-f60dcb00-26fa-11ea-86cb-dd2a1c4e3dc6.png)

类似这样的。

**Comment by Fechin** [comment]
主题已支持配置备案信息，移步README说明
